.github/workflows/build-ceph-daemon-container-image.yml
=> ceph-daemon: use v6.0.6-stable-6.0-pacific

.github/workflows/build-netbox-container-image.yml
=> netbox: re-enable 3.0.x builds and bump 3.1.x version

.github/workflows/build-keycloak-container-image.yml, keycloak/Containerfile, keycloak/Dockerfile
This image is necessary because we want to use Keycloak behind
raefik. In this case Keycloak is accessible via /keycloak/.
By default this does not work in the upstream Keycloak images.
=> Add keycloak image

ara-server/Containerfile
For some unknown reason the current builds of the ara-server container
fail to initialize their database. Rebuild the container on the standard
python base.
Fix some bugs in the Containerfile along the way.
Signed-off-by: Dr. Jens Harbott <harbott@osism.tech>
=> Fix ara-server image #40

.github/workflows/build-awxclient-container-image.yml, .github/workflows/build-ceph-daemon-container-image.yml, .github/workflows/build-cephclient-container-image.yml, .github/workflows/build-nova-libvirt-cloud-hypervisor-container-image.yml
- Ceph nautilus image is no longer available upstream
- cloud-hypervisor builds are failing and need a fix
- Latest awx releases are missing on pypi
Signed-off-by: Dr. Jens Harbott <harbott@osism.tech>
=> Stop running broken build actions

ceph-daemon/Containerfile
We removed Zabbix a long time ago. This is a leftover
and can be removed.
=> ceph-daemon: remove zabbix-sender

openstackclient/files/requirements.txt
Necessary to get results from osprofiler
=> openstackclient: install osprofiler package

virtualbmc/Containerfile
This reduces the image size by about 500 MByte.
=> virtualbmc: use slim python base image

cephclient/Containerfile
Remove packages that are no longer needed after the build.
This reduces the image size by about 500 MByte.
=> cephclient: reduze image size

netbox/requirements.txt
We need to store secrets for the deployment of the switch
configurations directly on the Netbox.
=> netbox: install netbox-secretstore

openstackclient/files/requirements.txt
dragon@5f1790f4aed7:~$ openstack bgp
openstack: 'bgp' is not an openstack command. See 'openstack --help'.
Did you mean one of these?
help
ip availability list
ip availability show
Related to osism/issues#209
=> openstackclient: install neutron-dynamic-routing

.github/workflows/build-nexus-container-image.yml
There is no latest image of Nexus. Therefore, the rebuild makes no sense.
=> nexus: disable rebuilds

ceph-daemon/Containerfile
upstream tags introduced a suffix '-x86_64' which is now added
Signed-off-by: Tim Beermann <beermann@osism.tech>
=> ceph-daemon: wrong image tag

homer/Containerfile
closes #132 
The upstream container tag introduced a prefix 'v' which now breaks our update automation causing a double 'v'. Therefore removed the hard coded 'v' in the container file.
Signed-off-by: Tim Beermann <beermann@osism.tech>
=> homer: upstream container tag changed

.github/workflows/build-netbox-container-image.yml, netbox/Containerfile
Upstream no longer builds the tag since version 3.2.5.
Closes osism/issues#376
=> netbox: use tag without -ldap

netbox/Containerfile, netbox/files/netbox-bgp-init.py
This is a temporary workaround to be able to work with Netbox 3.4.
Can be removed after merge & release of
https://github.com/k01ek/netbox-bgp/pull/117
=> netbox: fix "Plugin netbox_bgp requires NetBox maximum version 3.3.99."

netbox/Containerfile, netbox/files/launch.sh
In this script, commands can be added that are to be executed after the initialisation of Netbox and before the start of Netbox.
The initialisation of additional objects has been outsourced to a plug-in and must still be executed separately.
=> netbox: add launch.sh script

.zuul.yaml
- Enable flake8 check via zuul
- Partly osism/issues#397
Signed-off-by: Ramona Beermann <ramona.beermann@osism.tech>
=> Python: Add syntax check

.flake8, .github/workflows/build-aptly-container-image.yml, .github/workflows/build-aptly-nginx-container-image.yml, .github/workflows/build-aptly-prepare-container-image.yml, aptly/Containerfile-aptly, aptly/Containerfile-nginx, aptly/Containerfile-prepare, aptly/README.md, aptly/aptly.conf, aptly/main.py, aptly/nginx.aptly.conf, aptly/requirements.txt, prometheus-arista-eos-exporter/Containerfile
Aptly (and it's wrapper script) will be used to mirror a bunch of upstream repos.
Unfortunately, a preparation container, as well as a modded nginx are required to
consume aptly nearly fully automated. Only the GPG1 key needs to be created on first
installation within the preparation container (which terminates after succeeding):
```sh
gpg1 --gen-key
gpg1 --export --armor --output /opt/aptly/public/gpgkey OSISM
```
relates SovereignCloudStack/issues#334
relates osism/helm-charts#20
Signed-off-by: Tim Beermann <beermann@osism.tech>
=> Add aptly containers

netbox/requirements.txt
This reverts commit 4102c8cc9fc5429c127fd531513fbe77d4895d9b.
Not compatible with Netbox v3.4
=> Revert "chore(deps): update dependency netbox-initializers to v3.5.1"

cephclient/Containerfile
The osism.services.cephclient copy task expects the completion scripts in /etc/bash_completion.d/.
=> cephclient: add missing bash completion scripts

cephclient/Containerfile
The necessary packages are all included in ceph-common. It is not necessary to install everything from Ceph.
=> cephclient: use package 'ceph-common' instead of 'ceph'

openstackclient/Containerfile
The ospurge project is deprected in favor of the purge command of the openstack client.
=> openstackclient: remove ospurge

metering/Containerfile
This fixes
```
testbed-manager docker[231291]: Error response from daemon: unable to find user dragon: no matching entries in passwd file
```
=> fixes creating the metering user

.github/workflows/build-ceph-daemon-container-image.yml
There was a surprising release of Pacific.
https://ceph.io/en/news/blog/2024/v16-2-15-pacific-released/
=> ceph-daemon: re-enable pacific build

cephclient/Containerfile, scripts/build.sh
For quincy there are only bullseye packages.
For reef there are only bookworm packages.
=> cephclient: handle debian version

openstackclient/files/requirements.txt
Could not load 'metric_resource-type_create': No module named 'distutils'
Could not load 'metric_resource-type_delete': No module named 'distutils'
Could not load 'metric_resource-type_list': No module named 'distutils'
Could not load 'metric_resource-type_show': No module named 'distutils'
Could not load 'metric_resource-type_update': No module named 'distutils'
Could not load 'metric_resource_batch_delete': No module named 'distutils'
Could not load 'metric_resource_create': No module named 'distutils'
Could not load 'metric_resource_delete': No module named 'distutils'
Could not load 'metric_resource_history': No module named 'distutils'
Could not load 'metric_resource_list': No module named 'distutils'
Could not load 'metric_resource_search': No module named 'distutils'
Could not load …
=> openstackclient: install setuptools

tempest/Containerfile, tempest/files/requirements.txt
In the osism.validations.tempest role, there is something wrong with disabling services. But the errors are not with the versions here in the image.
=> tempest: bump versions (again)

ansible-lint/files/prepare-config.py
Since ansible-lint-24.10.0, the parsing of the config is partially failing if the yaml in to config file isn't preceded by the "---" marker. Make sure that it is preserved in the merged config file.
=> ansible-lint: Add explicit start to prepare-config

openstackclient/Containerfile
This solves the following problem. It can be removed in the future if netifaces is no longer used as a dependency of the OpenStack SDK.
netifaces.c:1808:9: error: initialization of 'int' from 'void *' makes integer from pointer without a cast [-Wint-conversion]
=> openstackclient: set CFLAGS="-Wno-int-conversion"

.github/workflows/build-homer-container-image.yml, homer/Containerfile
This avoids wrong versions like in osism/container-images#627
=> homer: use docker hub as source for renovate

openstackclient/Containerfile, openstackclient/files/requirements.extra.txt
This reverts commit 9124746f779220e22f95d9854f1adfbc9006ceca.
Since we are currently installing per system and not running the CLI as root, the execution is very slow.
=> Revert "openstackclient: use pyclean (#634)"

netbox/requirements.txt
The "4.2.6-Docker-3.2.0" issue is still not fixed.
=> netbox: remove netbox-topology-views plugin

openstackclient/Containerfile
We need xorriso in the runtime, don't remove it after building.
=> openstackclient: keep xorriso
