.github/workflows/build-netbox-container-image.yml
netbox/Containerfile

netbox: use v3.1.0-ldap

---

netbox/requirements.txt

netbox: add netbox-dns plugin & upgdate bgp plugin

---

.github/workflows/build-nexus-container-image.yml
nexus/Containerfile

nexus: use 3.37.0

---

.github/workflows/build-awxclient-container-image.yml

awxclient: 19.5.0

---

.github/workflows/build-ceph-daemon-container-image.yml

ceph-daemon: add nautilus build

---

.github/workflows/build-ara-server-container-image.yml
.github/workflows/build-awxclient-container-image.yml
.github/workflows/build-ceph-daemon-container-image.yml
.github/workflows/build-cephclient-container-image.yml
.github/workflows/build-github-actions-runner-cointainer-image.yml
.github/workflows/build-homer-container-image.yml
.github/workflows/build-jenkins-container-image.yml
.github/workflows/build-kosmoo-container-image.yml
.github/workflows/build-netbox-container-image.yml
.github/workflows/build-nexus-container-image.yml
.github/workflows/build-nova-libvirt-cloud-hypervisor-container-image.yml
.github/workflows/build-openstackclient-container-image.yml
.github/workflows/build-patchman-container-image.yml
.github/workflows/build-prometheus-arista-eos-exporter-container-image.yml
.github/workflows/build-tang-container-image.yml
.github/workflows/build-virtualbmc-container-image.yml
.github/workflows/check-docker-syntax.yml
.github/workflows/check-yaml-syntax.yml

github: run branch builds on main only

---

nexus/Containerfile
nexus/files/scripts/run.sh

nexus: fix healthcheck

---

nexus/files/scripts/delete.sh
nexus/files/scripts/enable-anonymous.sh
nexus/files/scripts/provision.sh

nexus: do not use wait

---

nexus/files/scripts/setup-proxy.json
nexus/files/scripts/update-admin-password.json

nexus: add scripts

---

.github/workflows/build-netbox-container-image.yml
netbox/Containerfile

netbox: version 3.1.2

---

.github/workflows/build-nexus-container-image.yml
nexus/Containerfile

nexus: version 3.37.3

---

nexus/files/scripts/setup-proxy.json
nexus/files/scripts/update-admin-password.json

nexus: move some scripts to the ansible role

---

nexus/files/scripts/docker-hub.json
nexus/files/scripts/docker-quay.json
nexus/files/scripts/ubuntu-archive.json
nexus/files/scripts/ubuntu-docker.json

nexus: move more scripts to the ansible role

---

.github/workflows/build-netbox-container-image.yml
netbox/Containerfile

netbox: version 3.1.3

---

.github/workflows/build-github-actions-runner-cointainer-image.yml

github-actions-runner: push latest tag

---

netbox/requirements.txt

netbox: netbox-dns 0.8.0

---

netbox/Containerfile
netbox/requirements.txt

netbox: install netbox-plugin-osism

---

.github/workflows/build-netbox-container-image.yml
netbox/Containerfile

netbox: version 3.1.5

---

.github/workflows/build-dnsdist-container-image.yml
dnsdist/Containerfile
dnsdist/Dockerfile

Based on tcely/dockerhub-powerdns

Add dnsdist image

---

.github/workflows/build-ara-server-container-image.yml
scripts/build.sh
scripts/push.sh

Use docker-slim

---

.github/workflows/build-ara-server-container-image.yml

github: add missing DOCKER_SLIM

---

netbox/requirements.txt

netbox: use netbox-bgp 0.5.0

---

.github/workflows/build-netbox-container-image.yml
netbox/Containerfile

netbox: version 3.1.6

---

.github/workflows/build-awxclient-container-image.yml

awxclient: use version 19.5.1

---

keycloak/Containerfile

Signed-off-by: Dr. Jens Harbott <harbott@osism.tech>

Bump keycloak container version

---

.github/workflows/build-netbox-container-image.yml
netbox/Containerfile

netbox: use v3.1.7

---

.github/workflows/build-awxclient-container-image.yml

awxclient: use version 20.0.0

---

.github/workflows/build-netbox-container-image.yml
netbox/Containerfile

netbox: use version 3.1.8

---

.github/workflows/build-nexus-container-image.yml
nexus/Containerfile

nexus: use version 3.38.0

---

.github/workflows/build-keycloak-container-image.yml
keycloak/Containerfile

keycloak: use version 17.0.0

---

.github/workflows/build-netbox-container-image.yml
netbox/Containerfile

netbox: use version 3.1.9

---

.github/workflows/build-cephclient-container-image.yml

cephclient: add quincy

---

scripts/push.sh

ceph-daemon: push osism/ceph-daemon:pacific

---

.github/workflows/build-ceph-daemon-container-image.yml

ceph-daemon: update versions

---

.github/workflows/build-openstackclient-container-image.yml
openstackclient/Containerfile

openstackclient: add zed future release

---

ara-server/Containerfile

ara-server: use slim python base image

---

.github/workflows/build-ceph-daemon-container-image.yml
ceph-daemon/Containerfile

ceph-daemon: fix base image

---

.github/workflows/build-patchman-container-image.yml
patchman/Containerfile
patchman/files/requirements.txt

patchman: install package from pypi

---

.github/workflows/build-ara-server-container-image.yml

ara-server: use version 1.5.8

---

ara-server/Containerfile

ara-server: use python 3.10

---

.github/workflows/build-ara-server-container-image.yml
ara-server/Containerfile

ara-server: install latest from git

---

.github/workflows/build-netbox-container-image.yml

netbox: remove 3.0.x

---

.github/workflows/build-netbox-container-image.yml
netbox/Containerfile

netbox: use 3.2.1

---

ara-server/Containerfile
openstackclient/Containerfile

Pin version of the pip package

---

netbox/Containerfile

netbox: fix installation of pycryptodome

---

.github/workflows/build-ceph-daemon-container-image.yml

ceph-daemon: update version

---

.github/workflows/build-ceph-daemon-container-image.yml

ceph-daemon: add quincy

---

homer/Containerfile

Signed-off-by: Tim Beermann <beermann@osism.tech>

Homer: removed dependency on tag in folder name

---

src/update-ceph-daemon-versions.py

Add quincy to update-ceph-daemon-versions.py

---

netbox/requirements.txt

netbox: install netbox-initializers

---

.github/workflows/build-ara-server-container-image.yml
ara-server/Containerfile
scripts/push.sh

ara-server: only build the latest stable version

---

ara-server/Containerfile

ara-server: remove VERSION argument

---

.github/workflows/build-ara-server-container-image.yml
.github/workflows/build-cgit-container-image.yml

github: add missing DOCKER_* parameters

---

ara-server/Containerfile

ara-server: use python 3.11

---

seed/files/run.sh

seed: k8s playbook requires parameters from infrastructure env

---

.github/workflows/build-dnsdist-container-image.yml

dnsdist: use version 1.7.3

---

.hadolint.yaml
ara-server/Containerfile
cephclient/Containerfile
dcap-register/Containerfile
dcap-server/Containerfile
dnsdist/Containerfile
openstackclient/Containerfile
patchman/Containerfile
prometheus-arista-eos-exporter/Containerfile

- Delete not needed rules
- Add explanation why we skip some rules
- Refactor code to fix issues
- Partly osism/issues#582
Signed-off-by: Ramona Beermann <ramona.beermann@osism.tech>

Hadolint: Refactor rules

---

ara-server/files/requirements.txt

This reverts commit a41d2cefda2470bb62543d1dc59a27f54b5596bc.
Further tests required with ARA 1.6.1.

Revert "chore(deps): update dependency gevent to v23"

---

ara-server/Containerfile

Fixes:
Exception: Can not find valid pkg-config name.
Specify MYSQLCLIENT_CFLAGS and MYSQLCLIENT_LDFLAGS env vars manually

ara-server: fix build

---

scripts/push.sh

Also reverts ad098fa9a88c4c3207225a32272f2777e6c5c98c since it is not required at all.

Push latest netbox image, do not overwrite versioned netbox image

---

seed/files/requirements.txt

Remove ruaeml.yaml

---

nexus/Containerfile

This reverts commit 4358ceaef7526b480abfed7c3055b7f3523a492a.

Revert "nexus: move logback directory (#409)"

---

ara-server/Containerfile
ceph-daemon/Containerfile
cephclient/Containerfile
cgit/Containerfile
dnsdist/Containerfile
homer/Containerfile
kosmoo/Containerfile
lloadd/Containerfile
metering/Containerfile
netbox/Containerfile
nexus/Containerfile
openstackclient/Containerfile
prometheus-redfish-exporter/Containerfile
seed/Containerfile
tang/Containerfile
virtualbmc/Containerfile

Part of https://github.com/osism/issues/issues/937

Replace https://osism.github.io/docs/intro with https://osism.tech/docs/

---

.github/workflows/build-openstackclient-container-image.yml

zuul: remove openstackclient zed jobs

---

.github/workflows/build-tempest-container-image.yml
tempest/Containerfile
tempest/Dockerfile
tempest/files/requirements.txt

Part of https://github.com/osism/issues/issues/926

Add tempest container

---

ara-server/files/requirements.txt

https://github.com/kludex/fastapi-tips?tab=readme-ov-file#1-install-uvloop-and-httptools

ara-server: install uvloop + httptools

---

openstackclient/Containerfile

openstackclient: install keystoneauth-websso

---

netbox/requirements.txt

Closes https://github.com/osism/ansible-collection-services/issues/1572

Update netbox requirements.txt

---

tempest/files/requirements.txt

This reverts commit f1d5cee59d6ccb3a97f0ac6be883fb9931d42168.

Revert "tempest: install more plugins (#577)"

---

tempest/Containerfile

This reverts commit 1896acfb7218f20b492356987bbb576e6c587721.

Revert "tempest: use python 3.13 (#576)"

---

netbox/files/launch.sh

netbox: collect static files

---

netbox/requirements.txt

netbox: remove netbox-ui plugin

---

.github/workflows/build-ansible-lint-container-image.yml
.github/workflows/build-ara-server-container-image.yml
.github/workflows/build-ceph-daemon-container-image.yml
.github/workflows/build-cephclient-container-image.yml
.github/workflows/build-cgit-container-image.yml
.github/workflows/build-dnsdist-container-image.yml
.github/workflows/build-dnsmasq-osism-container-image.yml
.github/workflows/build-homer-container-image.yml
.github/workflows/build-kosmoo-container-image.yml
.github/workflows/build-lloadd-container-image.yml
.github/workflows/build-netbox-container-image.yml
.github/workflows/build-nexus-container-image.yml
.github/workflows/build-openstackclient-container-image.yml
.github/workflows/build-prometheus-redfish-exporter.yml
.github/workflows/build-seed-container-image.yml
.github/workflows/build-sonic-vs-container-image.yml
.github/workflows/build-tempest-container-image.yml

Related to 5e0a3af305e472886bcc65bd1a485f2712600d68

github: add dtrack env vars

---

.github/workflows/build-tenks-container-image.yml
tenks/Containerfile
tenks/Dockerfile

Part of https://github.com/osism/issues/issues/1196

Add tenks container

---

.github/workflows/build-ansible-lint-container-image.yml
.github/workflows/build-ara-server-container-image.yml
.github/workflows/build-ceph-daemon-container-image.yml
.github/workflows/build-cephclient-container-image.yml
.github/workflows/build-cgit-container-image.yml
.github/workflows/build-dnsdist-container-image.yml
.github/workflows/build-dnsmasq-osism-container-image.yml
.github/workflows/build-gnmic-image.yml
.github/workflows/build-homer-container-image.yml
.github/workflows/build-kosmoo-container-image.yml
.github/workflows/build-lloadd-container-image.yml
.github/workflows/build-netbox-container-image.yml
.github/workflows/build-nexus-container-image.yml
.github/workflows/build-openstackclient-container-image.yml
.github/workflows/build-prometheus-redfish-exporter.yml
.github/workflows/build-rsync-container-image.yml
.github/workflows/build-seed-container-image.yml
.github/workflows/build-sonic-vs-container-image.yml
.github/workflows/build-tempest-container-image.yml
.github/workflows/build-tenks-container-image.yml

Related to 2e776aca9bd28c06955286e819f7fe795fcdce4e

github: add missing COSIGN env variables
